version:  "3"
services:
  simple:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:80
  oss:
    build:
      context: .
      dockerfile: oss.Dockerfile
      args:
        # 此处默认从宿主机(host)环境变量中传参，在宿主机中需要提前配置 ACCESS_KEY_ID/ACCESS_KEY_SECRET 环境变量
        - ACCESS_KEY_ID
        - ACCESS_KEY_SECRET
        - BUCKET=blog-1255502973
        - REGION=ap-shanghai
    ports:
      - 8000:80
